### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by zartan9** [DigitalDesignDude/DS-Game-Maker-5-Setup#2]
hi this looks great to make games for ds...DS Game Maker 5 Setup for Windows 11...im trying to follow the steps but got errors, please advise:  ![err](https://github.com/DigitalDesignDude/DS-Game-Maker-5-Setup/assets/74879950/99b05d4b-087c-4df7-bf00-9ef3fb70e985)
![or](https://github.com/DigitalDesignDude/DS-Game-Maker-5-Setup/assets/74879950/9d91f647-05e1-4935-8e67-f35e19c68037)

**Comment by DigitalDesignDude** [comment]
@zartan9, you can get help with this issue from the DS Game Maker Discord server linked below:

https://discord.gg/uzNM8gGSA4

For the most part installation issues like this are solved from the user's end and may require additional troubleshooting or configurations set on their computer.

**Comment by zartan9** [comment]
:) thanks i ran as admin and is solved! I think i may need to pay someone to help me on my game ideas using this promising software ill look for a "for hire: 
section on dischord
